### ISSUE TITLE
電子版が買いたい

### ISSUE THREAD

**Issue by lucioseki** [amane-uehara/cpubook#1]
サポートページを読んで読みたくなりました。
海外に住んでいるので、ぜひKindle版も出版してほしいです。

**Comment by amane-uehara** [comment]
はじめまして！著者です！
本書は電子版も発行予定です。
pdfバージョンと、AmazonのKindle版が出るはずです。

まだサイトに情報が出ていませんが、書籍版と同時に発売されるはずですので、来週までお待ち下さい～
<https://book.mynavi.jp/ec/products/detail/id=116654>
