### ISSUE TITLE
【サイト】「対応千ｕ」→「対応する」

### ISSUE THREAD

**Issue by sinato** [amane-uehara/cpubook#17]
**サポートサイト内ページのURL**
https://amane-uehara.github.io/cpubook/compile/

**不備の詳細**
細かいですがタイポを見つけました「対応千ｕ」→「対応する」　以下の行です。
https://github.com/amane-uehara/cpubook/blame/83c228c02656cce9c539b891ab9724d5d30bbbeb/compile/index.md#L159

**Comment by amane-uehara** [comment]
typo fix
