### ISSUE TITLE
【その他】 色覚異常用のpdfのリンク先がありません

### ISSUE THREAD

**Issue by KIICHISUDO** [amane-uehara/cpubook#19]
色覚異常用のpdfのリンク先が存在しません。
マイナビ側の問題でしょうが、別の場所で入手できると嬉しいです。

**Comment by amane-uehara** [comment]
@KIICHISUDO ご報告ありがとうございます。ご不便をおかけして申し訳ありません🙇‍♂️

早速修正いたしました。
https://github.com/amane-uehara/cpubook/commit/44b6dd978b47a32fbf6bf05918deebdf602b0709

下記ページから、マイナビに色違いバージョンのPDFを請求できます。
https://book.mynavi.jp/ec/products/detail/id=116654

ご不便をおかけしましたが、今後ともよろしくお願いいたします。

**Comment by KIICHISUDO** [comment]
ご対応ありがとうございます！
