### ISSUE TITLE
【誤植】[第1刷][88ページ] 字句修正

### ISSUE THREAD

**Issue by bonten** [amane-uehara/cpubook#20]
脚注18

「これは入力ポートなの方程式の右辺値になる」

「なの」を修正する必要があると思いますが、どう直すべきかは分かりません。

**Comment by amane-uehara** [comment]
@bonten 
誤植のご報告ありがとうございます！大変助かります。

誤植リストに追加いたしました。次の刷で修正しようと思います。
https://github.com/amane-uehara/cpubook/commit/c8aaf2b8f5608d6348df6a7fa4183c99d8d68448
